name: i18n_extension_importer
description: Text Importer for i18n_extension
version: 0.0.1
repository: https://github.com/c0dezli/i18n_extension_importer

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  gettext_parser: ^0.2.0

dev_dependencies:
  analyzer: any
  flutter_test: any
  lints: ^2.0.0
  test: ^1.21.0
